version: '3.9'

services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./app/out/:/app/out/
      - ./app/cache/:/app/cache/
    command: python main.py
    working_dir: /app
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: mysql
      DOCKER_CONTAINER: 1
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/db/setup.sh:/docker-entrypoint-initdb.d/setup.sh:ro
      - ./app/db/schema.sql:/app/db/schema.sql:ro
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      retries: 5
volumes:
  db_data:
